#!/usr/bin/env python3
"""
Generate a Markdown reference for raccoon-cli from its Click command tree.

This is intended to keep docs honest: it extracts command names, help text,
arguments, and options from the actual implementation in `raccoon/toolchain/`.

Usage:
  python tools/generate_cli_reference.py > content/04-raccoon-cli/99-command-reference.md
"""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class CmdNode:
    path: tuple[str, ...]
    cmd: "click.Command"


def _iter_command_tree(root_cmd: "click.Command", path: tuple[str, ...] = ()) -> Iterable[CmdNode]:
    import click

    yield CmdNode(path=path, cmd=root_cmd)
    if isinstance(root_cmd, click.Group):
        for name, sub in root_cmd.commands.items():
            yield from _iter_command_tree(sub, path + (name,))


def _fmt_opt(p: "click.Parameter") -> str:
    import click

    if isinstance(p, click.Argument):
        # Arguments in Click don't have flags.
        arg_name = p.human_readable_name
        nargs = getattr(p, "nargs", 1)
        if nargs == -1:
            arg_name = f"{arg_name}..."
        return f"- `{arg_name}` (argument)"

    if isinstance(p, click.Option):
        opts = list(p.opts) + list(p.secondary_opts)
        flags = ", ".join(f"`{o}`" for o in opts if o)
        pieces: list[str] = [f"- {flags}"]
        if p.required:
            pieces.append("(required)")
        if p.is_flag:
            pieces.append("(flag)")
        if p.multiple:
            pieces.append("(repeatable)")
        # Default handling: Click uses None a lot; prefer to show only when meaningful.
        if p.default not in (None, (), []):
            pieces.append(f"(default: `{p.default}`)")
        help_text = (p.help or "").strip()
        if help_text:
            pieces.append(f"  {help_text}")
        return " ".join(pieces)

    return f"- `{p.name}`"


def _md_escape(s: str) -> str:
    return s.replace("\r\n", "\n").replace("\r", "\n").strip()


def main() -> int:
    import click

    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
    toolchain_path = os.path.join(repo_root, "raccoon", "toolchain")
    sys.path.insert(0, toolchain_path)

    from raccoon_cli.cli import main as raccoon_main

    lines: list[str] = []
    lines.append("---")
    lines.append('title: "Command Reference (Generated)"')
    lines.append('author: "Docs Bot"')
    lines.append("date: 2026-05-28")
    lines.append("draft: false")
    lines.append("weight: 99")
    lines.append('description: "Autogenerated reference of every raccoon command/flag from the Click command tree."')
    lines.append("---")
    lines.append("")
    lines.append("# Command Reference (Generated)")
    lines.append("")
    lines.append(
        "This page is generated from the actual CLI implementation under `raccoon/toolchain/`.\n"
        "Do not edit by hand; update the CLI or the generator instead."
    )
    lines.append("")

    nodes = list(_iter_command_tree(raccoon_main, ()))
    # Stable ordering: by command path.
    nodes.sort(key=lambda n: n.path)

    for node in nodes:
        cmd = node.cmd
        path = " ".join(("raccoon",) + node.path) if node.path else "raccoon"
        heading = path
        depth = 2 if node.path else 1
        lines.append("#" * depth + f" `{heading}`")
        lines.append("")

        help_text = _md_escape(cmd.help or cmd.short_help or "")
        if help_text:
            lines.append(help_text)
            lines.append("")

        # Usage
        usage = cmd.get_usage(click.Context(cmd, info_name=heading))
        usage = _md_escape(usage)
        if usage:
            lines.append("```text")
            lines.append(usage)
            lines.append("```")
            lines.append("")

        # Parameters (arguments + options)
        params = list(cmd.params or [])
        if params:
            lines.append("**Arguments & Options**")
            lines.append("")
            for p in params:
                lines.append(_fmt_opt(p))
            lines.append("")

        # Subcommands list for groups
        if isinstance(cmd, click.Group) and cmd.commands:
            lines.append("**Subcommands**")
            lines.append("")
            for name in sorted(cmd.commands.keys()):
                sub = cmd.commands[name]
                desc = _md_escape(sub.short_help or sub.help or "")
                if desc:
                    lines.append(f"- `{path} {name}`  {desc}")
                else:
                    lines.append(f"- `{path} {name}`")
            lines.append("")

    sys.stdout.write("\n".join(lines).rstrip() + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
